AllCops:
  TargetRubyVersion: 2.6

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Lint/RedundantRequireStatement:
  Enabled: true

Lint/UselessComparison:
  Enabled: true

Lint/UselessElseWithoutRescue:
  Enabled: true

Lint/UselessSetterCall:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: "double_quotes"

Style/EndBlock:
  Enabled: true
